"""empty message

Revision ID: 7e8102696f97
Revises: f344eb966fd7
Create Date: 2023-10-25 13:24:43.612059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8102696f97'
down_revision = 'f344eb966fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_no', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactus', schema=None) as batch_op:
        batch_op.drop_column('contact_no')

    # ### end Alembic commands ###
