"""empty message

Revision ID: f344eb966fd7
Revises: 0d3c9087b839
Create Date: 2023-10-25 13:23:40.647745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f344eb966fd7'
down_revision = '0d3c9087b839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactus',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_message', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('contact_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contactus')
    # ### end Alembic commands ###
